### ISSUE TITLE
Incorporate reading and writing to IPFS in the DApp itself

### ISSUE THREAD

**Issue by raamb** [singnet/snet-rfai-dapp#13]
We are currently using an API to write and read data from IPFS, lets do this as part of the DApp code itself

**Comment by ksridharbabuus** [comment]
Now the request metadata like:
- - title 
- - description
- - documentURI
- - author
- - training-dataset
- - acceptance-criteria
- - created

 is available in ipfs and the hash is stored in the contract.

**Comment by ksridharbabuus** [comment]
Completed it long back, closing it now.
