### ISSUE TITLE
Label "Amount" crosses the borders of field with its value (minor UI bug) +

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#15]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
1. Observe the page

**EXPECTED RESULT:**

Label "Amount" doesn't cross the borders of field with its value

**ACTUAL RESULT:**

Label "Amount" crosses the borders of field with its value

**Please see the screenshot below**

![2019-04-05_03h11_48](https://user-images.githubusercontent.com/12077703/55597065-6d0dc880-5754-11e9-8918-490b2538aaff.png)

**Comment by ksridharbabuus** [comment]
@raamb Can you please request Ananya to look into this UI changes.

**Comment by raamb** [comment]
This is as per the UX design and is not an issue

**Comment by rustam-snet** [comment]
Ok, more detailed opinion in comments to that issue #25
