### ISSUE TITLE
Labels "Your Balance in Escrow" and "Funding Amount" cross the borders of fields with its values (minor bug) +

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#24]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Scroll down to the first request on "Active" tab
3. Expand info about this request
4. Press "Fund this project" button
5. Observe the fields in opened window

**EXPECTED RESULT:**

Labels "Your Balance in Escrow" and "Funding Amount" don't cross the borders of fields with its values
ACTUAL RESULT: Labels "Your Balance in Escrow" and "Funding Amount" cross the borders of fields with its values

**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Please see the video below**

![20190405_07h04_02](https://user-images.githubusercontent.com/12077703/55603082-8a9d5b00-5771-11e9-9d92-46ccbc1e672a.gif)

Note: This bug looks pretty similar to this one https://github.com/singnet/snet-rfai-dapp/issues/15 but they are related to different windows so I decided to not mix them all in one issue. Approach with mixing can lead to the result where not all fields will be fixed (as a result of human factor).

**Comment by ksridharbabuus** [comment]
@raamb can you please request Ananya to fix the UI issue. Thanks

**Comment by raamb** [comment]
This is expected, its as per the UX provided for the Dapp

**Comment by rustam-snet** [comment]
Ok, I agree, more detailed opinion in comments to that issue https://github.com/singnet/snet-rfai-dapp/issues/25
