### ISSUE TITLE
Label "Github Link" crosses the border of field with its value (minor bug) +

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#25]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Scroll down to the first request on "Active" tab
3. Expand info about this request
4. Press "Submit solution" button
5. Observe the fields in opened window

**EXPECTED RESULT:**

Label "Github Link" doesn't cross the borders of fields with its values

**ACTUAL RESULT:**

Label "Github Link" crosses the borders of field with its value

**Please see the video below**

![20190405_07h22_04](https://user-images.githubusercontent.com/12077703/55603499-a43fa200-5773-11e9-9b42-6e10cbc93e27.gif)

**Comment by ksridharbabuus** [comment]
@raamb can you please request Ananya to fix the UI issue. Thanks

**Comment by raamb** [comment]
This is as per the UX provided

**Comment by rustam-snet** [comment]
Ok, if it's per requirements then in this particular case I can agree, this design can be perceived as original /interesting one. Thanks Raam.
