### ISSUE TITLE
System redirects user to Home Page if he / she refreshes the "Account" page (bug)

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#31]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Press "ADD MORE FUNDS" button or press "Account" button in the right upper corner
3. Wait until the "Account" page will appear
4. Press browser refresh button (or hot key F5 on Windows)
5. Observe the result

**EXPECTED RESULT:**

I expected that user will stay on Account page

**ACTUAL RESULT:** 

System redirected user to the Home Page

**Please see the video below**

![20190405_19h55_18](https://user-images.githubusercontent.com/12077703/55644138-a9393b80-57dd-11e9-8cb4-1124589db495.gif)

**Comment by ksridharbabuus** [comment]
Any where in the app, if user refreshes the page it goes to the Request Listing page as we dont store the state of the navigation.
Current functionality is as per the implementation.

Based on the requirements we can implement the same.

**Comment by ksridharbabuus** [comment]
Added Routers logic Should fix this issue.

**Comment by rustam-snet** [comment]
Fix is verified, thanks
