### ISSUE TITLE
Can't submit a request for 1 AGI with 1 AGI in escrow (bug)

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#32]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Precondition:**

User has 1 AGI on escrow balance

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Press "Create" button in the right upper corner of the screen
3. Navigate to the "Submit Request" in opened window
4. Fill all fields like on the video below (the main point is that you should type 1 in the "Initial Funding Amount" field)
5. Press "Submit"
6. Observe the result

**EXPECTED RESULT:**

System has submitted the request

**ACTUAL RESULT:**

User sees such an error message
"Oops! You dont have enough token balance in RFAI Escrow."

**Note:**

I suppose the reason can be related to the situation when user tries to deposit exactly as much AGI tokens as he / she has. Because when I had set 0,5 AGI as a funding amount and pressed "Submit" once more I got another error message with such a text
"Oops! Invalid Github handle."

**Please see the video below**

![20190405_20h33_25](https://user-images.githubusercontent.com/12077703/55645945-907f5480-57e2-11e9-9edc-47fefd4431a6.gif)

**Comment by ksridharbabuus** [comment]
Fixed the issue. It might caused by the number limits on git API calls. Now changed the git call only onBlur rather than every call.

Issue is fixed.

**Comment by rustam-snet** [comment]
Fix is verified, thanks
