### ISSUE TITLE
Can't open pages for "Create", "Account" and "View Requests" options in new tabs (bug) -

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#35]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Try to open "Create" page in new tab (using "Create" button)
3. Try to open "Account" page in new tab (using "Account" button)
4. Try to open "View Requests" page in new tab (using "View Requests" button)
5. Observe the result

**EXPECTED RESULT:**

We can see three tabs

- The first one with opened "Create Request" page (with steps "Overview", "Evaluation", "Process", "Submit Request")
- The second one with opened "Account" page (with "Your Account Details" and "Manage Your RFAI Account")
- The third one with visible "Requests for AI Services" list

**ACTUAL RESULT:**

- The first one with Home Page
- The second one with Home Page
- The third one with Home Page. We can actually see "Requests for AI Services" list here but we can always see it on the Home Page so I suppose that proper opening in the new tabs isn't implemented for all these buttons ("Create", "Account" and "View Requests")

**Please see the video below**

![20190408_04h55_16](https://user-images.githubusercontent.com/12077703/55694017-bfe8b980-59ba-11e9-8507-c5d6eb127986.gif)

**Comment by ksridharbabuus** [comment]
That is as per the expected behaviour. Those needs to be opened in the current browser instance. If this functionality is needed we can enable the same and I dont this it is required for now.

**Comment by rustam-snet** [comment]
Well, on the one hand I am not sure that it's critical to provide such functionality asap indeed but on the other hand it doesn't really look as nice user experience that we show user the same Home Page in case of trying to open specific options (Create, Account etc) in the other tab. So I still think that it's better to make it possible to open "Create", "Account" and "View Requests" in the other tab.

**Comment by ksridharbabuus** [comment]
Added this functionality by adding Routes in the ReactJS SPA App.

Issue is fixed.

**Comment by rustam-snet** [comment]
You are welcome. Fix is verified, thanks.
