### ISSUE TITLE
After depositing of the authorized tokens system shows them both in authorized and deposited ones until the page refresh (bug)

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#39]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
Press names of "Active", "Completed" and "Expired" tabs one by one
Observe the borders around these names

**EXPECTED RESULT:**

I think that it could look better if user only saw the bottom border (line under the name of the tab)

**ACTUAL RESULT:**

User sees some borders around the name of each tab. By the way when user clicks somewhere outside of these names then all borders (except the bottom one) disappear

**Please see the video below**

![20190408_08h21_28](https://user-images.githubusercontent.com/12077703/55700416-d5201100-59d7-11e9-81e1-c8a94fcc5d63.gif)

**Please see the screenshot after the refreshing of the page**

![2019-04-08_08h23_05](https://user-images.githubusercontent.com/12077703/55700424-db15f200-59d7-11e9-829e-b508a0793532.png)

**Comment by ksridharbabuus** [comment]
Looks like there is a bug in Drizzle in Syncronizing the Token Contract. Explicitly made a Blockchain call  to refresh the data for Token Balance and Allowance.
Issue is fixed.

**Comment by rustam-snet** [comment]
You are welcome. Fix is verified, thanks.
