### ISSUE TITLE
Solution URI value should be a link (enhancement / bug)

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#43]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Choose "Completed" tab in the "Requests for AI Services" section
3. Open the details of "Non title provided" request
4. Press "View solution"
5. Observe the result

**EXPECTED RESULT:**

Value in "Solution URI" column should be a link

**ACTUAL RESULT:**

I see such links

- http://github.com/ksridharbabuus/project1
- https://github.com/s5

But in the format of plain text

**Please see the video below**

![20190410_07h41_22](https://user-images.githubusercontent.com/12077703/55852135-61f7d580-5b64-11e9-866c-4711ad07c74a.gif)

**Comment by ksridharbabuus** [comment]
Enabled it as a hyperlink. Thanks for the Suggestion @rustam-snet

**Comment by rustam-snet** [comment]
You are welcome. Fix is verified, thanks.
