### ISSUE TITLE
api to write rfai json data to ipfs

### ISSUE THREAD

**Issue by prashantramangupta** [singnet/snet-rfai-dapp#6]
separate lambda and gateway setup and API to write rfai JSON data to ipfs.

**Comment by prashantramangupta** [comment]
/ipfs
method: POST
Request:{
    "test": "dummy"
}
Response:{
    "status": "success",
    "data": {
        "hash": "QmRxQk3apyv6yZQDTc54SfpVQ6CGnNwho6hZ56ajEd3VH2"
    }
}
@raamb pls review and close this issue.

**Comment by ksridharbabuus** [comment]
This is working and integrated into the DApp as well. 
We can close the request.
